Global:
  use_gpu: True
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/rec/svtr_ALPR_v2_64x256_041223_DD/
  save_epoch_step: 10
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: ./pretrained/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ./dict/plate.txt
  character_type: en
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/svtr/predicts_svtr_tiny.txt
  d2s_train_image_shape: [3, 64, 256]


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize: [32, 64]
    tps_outputsize: [32, 100]
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size: [32, 100]
    out_char_num: 25 # W//4 or W//8 or W/12
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [64, 128, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer: ['Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    # mixer: ['Conv','Conv','Conv','Conv','Conv','Conv','Global','Global','Global','Global','Global','Global']
    # local_mixer: [[5, 5], [5, 5], [5, 5]]
    last_stage: True
    prenorm: False
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/jovyan/sonnt373/data/ALPR_OCR/251123_train_plate_gen_250k
    label_file_list:
      - /home/jovyan/sonnt373/data/ALPR_OCR/251123_train_plate_gen_250k/train_refactor.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SVTRRecAug:
          aug_type: 1 # or 1
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          image_shape: [3, 64, 256]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 32

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/jovyan/sonnt373/data/ALPR_OCR/251123_train_plate_gen_250k
    label_file_list:
      - /home/jovyan/sonnt373/data/ALPR_OCR/251123_train_plate_gen_250k/val.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SVTRRecAug:
          aug_type: 0 # or 1
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          image_shape: [3, 64, 256]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 256
    num_workers: 32


    # python3 tools/train.py -c /home/jovyan/PaddleOCR/configs/rec/pdf_svtr.yml -o Global.pretrained_model=/home/jovyan/PaddleOCR/output/rec/svtr_cccd/best_accuracy